name: peerlink
description: "Privacy-focused peer-to-peer file transfer app with WebRTC and
  Firebase signaling."
publish_to: "none"
version: 0.1.0+1
homepage: https://github.com/jhonny1994/peerlink
repository: https://github.com/jhonny1994/peerlink

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.0.3
  crypto: ^3.0.6
  desktop_drop: ^0.7.0
  file_picker: ^10.3.3
  file_selector: ^1.0.4
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  flutter_riverpod: ^3.0.3
  flutter_webrtc: ^1.2.0
  freezed_annotation: ^3.1.0
  haptic_feedback: ^0.5.1+1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mobile_scanner: ^7.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  qr_flutter: ^4.1.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/src/shared/localization/l10n
  output_dir: lib/src/shared/localization/generated
